worker_processes 1;

events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 80;
        server_name _;

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ =404;
        }

        location /login {
            proxy_pass http://backend:8000/login;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization';
            if ($request_method = 'OPTIONS') {
                return 204;
            }
        }
        location /register {
            proxy_pass http://backend:8000/register;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization';
            if ($request_method = 'OPTIONS') {
                return 204;
            }
        }
        # Adicione outros endpoints de API conforme necessário
    }
}
