  db:
    image: postgres:16
    container_name: promox-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: cbadmin
      POSTGRES_PASSWORD: Leozinho191095@
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
version: '3.8'
services:
  backend:
    build: ./backend
    container_name: promox-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: promox-frontend
    ports:
      - "7001:80"
    # volumes removido, arquivos copiados na build
